name: afficher message

on:
  push:
    branches: ["main"]

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest
    steps:
      - name: affichage
        run: echo "Hello world!"

  genrer-rapport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: generer rapport
        run: git diff --numstat HEAD~1 HEAD > rapport.txt

      - name: upload rapport
        uses: actions/upload-artifact@v4
        with:
          name: rapport
          path: rapport.txt
