name: exercice 3

on:
  push:
    branches: ["main"]

jobs:
  executer-java:
    runs-on: ubuntu-latest
    steps:
      - name: installer java
        uses: actions/setup-java
        with:
          java-version: '25'

      - name: recuperer le code
        uses: actions/checkout@v4

      - name: compiler le code
        run: mvn -B package

      - name: executer le code
        run: mvn -q exec:java -Dexec.mainClass=Main